version: '3.8'


services:
  db:
    container_name: ${PROJECT_NAME}_database
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST="${POSTGRES_HOST}"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure


volumes:
  postgres_data:

